spring:
  application:
    name: expense-management-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
  docker:
    compose:
      enabled: false
logging:
  file:
    path: ./data/logs
server:
  servlet:
    context-path: /api
