spring:
  application:
    name: expense-management-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  docker:
    compose:
      enabled: false
logging:
  file:
    name: ./data/logs/${spring.application.name}.log
server:
  servlet:
    context-path: /api
